'use client';
import { useMemo, useState } from 'react';
import { parseCSV, normalizeRows, summarize, forecastCoverage, transferPlan, dataQuality, exportActions, generateDemoCSV } from '@/lib/workforce.mjs';

const fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:1});
const pct=n=>`${(n*100).toFixed(0)}%`;
function download(name,text,type='text/csv'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);}

export default function Page(){
  const [rows,setRows]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const [horizon,setHorizon]=useState(14),[util,setUtil]=useState(85),[quantile,setQuantile]=useState(90),[selected,setSelected]=useState(null);
  const summary=useMemo(()=>summarize(rows),[rows]);
  const forecast=useMemo(()=>forecastCoverage(rows,{horizon,targetUtilization:util/100,serviceQuantile:quantile/100}),[rows,horizon,util,quantile]);
  const actions=useMemo(()=>transferPlan(forecast),[forecast]);
  const quality=useMemo(()=>dataQuality(rows),[rows]);
  const shortages=forecast.filter(x=>x.status==='SHORTAGE');
  const firstDate=forecast[0]?.date;
  const dayRows=forecast.filter(x=>x.date===firstDate);
  async function ingest(text){setLoading(true);setError('');await new Promise(r=>setTimeout(r,120));const n=normalizeRows(parseCSV(text));if(n.errors.length&&n.rows.length===0){setError(n.errors.slice(0,4).join(' '));setRows([]);}else{setRows(n.rows);setSelected(null);setError(n.errors.length?`${n.errors.length} invalid row(s) skipped.`:'');}setLoading(false);}
  async function demo(){ingest(generateDemoCSV());}
  async function file(e){const f=e.target.files?.[0];if(!f)return;ingest(await f.text());}
  return <main>
    <header className="top"><div><div className="eyebrow">DAY 16 · OPERATIONS DATA SCIENCE</div><h1>Workforce <span>Lens</span></h1></div><div className="trust">Browser-local analysis · No employee score</div></header>
    {!rows.length ? <section className="hero">
      <div className="heroCopy"><div className="pill">STAFFING CAPACITY & COVERAGE LAB</div><h2>Know where your schedule breaks <em>before</em> the shift starts.</h2><p>Forecast team-level demand, quantify coverage risk, and turn excess capacity into a practical reallocation plan. Built for operations teams—not employee surveillance.</p><div className="actions"><label className="primary">Upload workforce CSV<input type="file" accept=".csv,text/csv" onChange={file}/></label><button onClick={demo}>Try live demo</button><a href="/sample-workforce.csv" download>Download template</a></div>{loading&&<div className="loading">Analyzing staffing history…</div>}{error&&<div className="error">{error}</div>}</div>
      <div className="heroPanel"><div className="signal"><span>01</span><b>Learn</b><small>weekday demand + recent trend</small></div><div className="signal"><span>02</span><b>Stress</b><small>bootstrap uncertainty, not fake certainty</small></div><div className="signal"><span>03</span><b>Act</b><small>reallocate hours before adding capacity</small></div></div>
    </section> : <>
      <section className="toolbar"><div><b>Coverage scenario</b><small>{rows.length.toLocaleString()} source rows · {summary.teams.length} teams</small></div><div className="controls"><label>Horizon <select value={horizon} onChange={e=>setHorizon(+e.target.value)}><option value="7">7 days</option><option value="14">14 days</option><option value="21">21 days</option></select></label><label>Target utilization <input type="range" min="70" max="95" value={util} onChange={e=>setUtil(+e.target.value)}/><b>{util}%</b></label><label>Service protection <select value={quantile} onChange={e=>setQuantile(+e.target.value)}><option value="50">Median</option><option value="80">80th pct</option><option value="90">90th pct</option></select></label></div></section>
      <section className="kpis"><article><small>Observed demand</small><b>{fmt(summary.totalDemand)}</b><span>Known from uploaded data</span></article><article><small>Absence hours</small><b>{fmt(summary.totalAbsence)}</b><span>Known from uploaded data</span></article><article><small>Coverage alerts</small><b>{shortages.length}</b><span>Simulation-informed</span></article><article><small>Actionable reallocations</small><b>{actions.filter(a=>a.kind==='REALLOCATE').length}</b><span>Planning heuristic</span></article></section>
      <section className="grid">
        <article className="card wide"><div className="cardHead"><div><small>FORWARD COVERAGE</small><h3>Where the schedule is likely to break</h3></div><div className="legend"><span className="dot red"/>Shortage <span className="dot green"/>Excess</div></div><div className="forecastList">{forecast.slice(0,Math.min(28,forecast.length)).map((r,i)=><button key={i} className={`forecastRow ${r.status.toLowerCase()}`} onClick={()=>setSelected(r)}><span>{r.date.slice(5)}</span><strong>{r.team}</strong><span>p{quantile} need {fmt(r.requiredHours)}h</span><span>baseline {fmt(r.baseCapacity)}h</span><b>{r.gap>0?'+':''}{fmt(r.gap)}h</b></button>)}</div></article>
        <article className="card"><small>FIRST FORECAST DAY</small><h3>{firstDate}</h3><div className="bars">{dayRows.map(r=><div key={r.team}><div className="barLabel"><span>{r.team}</span><b>{r.status}</b></div><div className="bar"><i style={{width:`${Math.min(100,(r.requiredHours/Math.max(r.requiredHours,r.baseCapacity))*100)}%`}}/></div><small>{fmt(r.baseCapacity)} baseline hours → {fmt(r.requiredHours)} protected need</small></div>)}</div></article>
        <article className="card"><small>WORKLOAD CONCENTRATION</small><h3>Team-level balance signals</h3>{summary.teams.map(t=><div className="teamLine" key={t.team}><div><b>{t.team}</b><small>{t.headcount} people · observed utilization {pct(t.utilization)}</small></div><span>{pct(t.concentration)}<small> top-20% share</small></span></div>)}<p className="note">This is a team workload distribution signal, not an employee performance score.</p></article>
        <article className="card wide"><div className="cardHead"><div><small>CAPACITY ACTION PLAN</small><h3>Reallocate before you add hours</h3></div><button className="export" disabled={!actions.length} onClick={()=>download('workforce-lens-actions.csv',exportActions(actions))}>Export CSV</button></div>{actions.length?<div className="actionTable"><div className="tr head"><span>Date</span><span>Action</span><span>From</span><span>To</span><span>Hours</span></div>{actions.slice(0,18).map((a,i)=><div className="tr" key={i}><span>{a.date.slice(5)}</span><span className={a.kind==='REALLOCATE'?'good':'warn'}>{a.kind==='REALLOCATE'?'Reallocate':'Add capacity'}</span><span>{a.from}</span><span>{a.to}</span><b>{fmt(a.hours)}h</b></div>)}</div>:<div className="empty">No material coverage gap in this scenario.</div>}</article>
        <article className="card"><small>DATA READINESS</small><h3>Can you trust this forecast?</h3>{quality.map(q=><div className={`quality ${q.level}`} key={q.label}><div><b>{q.label}</b><span>{q.value}</span></div><small>{q.note}</small></div>)}</article>
        <article className="card honesty"><small>CONFIDENCE & HONESTY</small><h3>What this product is—and isn’t</h3><p><b>Known:</b> schedules, absence, productive hours, observed demand.</p><p><b>Statistical estimate:</b> weekday/trend demand pattern and bootstrap uncertainty.</p><p><b>Heuristic:</b> hour reallocation suggestions.</p><p><b>Not claimed:</b> employee productivity, burnout diagnosis, hiring/firing recommendations, or guaranteed service levels.</p></article>
      </section>
      <div className="reset"><button onClick={()=>setRows([])}>Analyze another file</button></div>
      {selected&&<div className="drawerBackdrop" onClick={()=>setSelected(null)}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><small>FORECAST EVIDENCE</small><h2>{selected.team}</h2><p>{selected.date}</p><div className="drawerStats"><div><span>Median demand</span><b>{fmt(selected.demandP50)}</b></div><div><span>Protected demand</span><b>{fmt(selected.demandRisk)}</b></div><div><span>Observed productivity</span><b>{fmt(selected.productivity)} u/h</b></div><div><span>Baseline capacity</span><b>{fmt(selected.baseCapacity)}h</b></div><div><span>Required hours</span><b>{fmt(selected.requiredHours)}h</b></div><div><span>Coverage gap</span><b>{selected.gap>0?'+':''}{fmt(selected.gap)}h</b></div></div><div className="method"><b>Why this number?</b><p>Workforce Lens learns the team’s weekday demand pattern and recent linear trend, resamples historical residuals 400 times, takes your selected service-protection quantile, then converts demand to hours using observed team productivity and your target utilization.</p></div></aside></div>}
    </>}
    <footer><b>Why this is not just another workforce dashboard</b><p>Dashboards describe last week. Workforce Lens converts uncertainty into a forward coverage plan while deliberately avoiding individual employee scoring.</p></footer>
  </main>
}
